### ISSUE TITLE
Github Auth Failure

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#1]
Failure to authenticate with Github through the route `login/github/`.

Unless I am an idiot and I did not hook that part up correctly in the `EJS`... Which is entirely possible.

```
<a href="/login/github" class="btn btn-block btn-lg btn-raised btn-default"><i class="fa fa-github pull-left"></i>Login with Github</a>
```

**Comment by sotch-pr35mac** [comment]
I can't seem to find the page with the GitHub API Settings so I can see some of the settings I set up, the code on our server side seems to be working, it is just not logging the user in, and then callining the failureRedirect which is set at the login page

**Comment by sotch-pr35mac** [comment]
issue has been fixed in the latest commit
