### ISSUE TITLE
Create UI / UX Connection to backend for project pages

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#11]
Because the dashboard concept of now is going to be repurposed into the specific project page, we need to create the connections between all of the pages.  
- [x] Pass projects to their own pages
    - How that is done is up to the discretion of @sotch-pr35mac 
- [x] Create project specific settings
    - This one is up for debate... We can have it on the main projects page
- [x] Configure breadcrumbs for easy navigation

**Comment by sotch-pr35mac** [comment]
I will let @steventhanna configure the breadcrumbs, i can go ahead and take of the routes for you though.

**Comment by sotch-pr35mac** [comment]
How is this different than #12 ?

**Comment by steventhanna** [comment]
My name was next to some of those tasks earlier, but the system must have taken them out because I create the issue...

This is different than #12 because these are pages specific to each individual project, while the dashboard referenced in #12 is an account wide overview, or analytics over all project and account activity.

**Comment by sotch-pr35mac** [comment]
So what I think we should do is make it all about GitHub Integration, so we should integrate the github issues, collaborators, projects, and everything, it would be a pretty big undertaking, So it would take sometime, i suggest making that a v1.0 kinda thing, and not a v0.1 kinda thing, if you know what I mean. This also has to do with Issue #13. 

More on the issue of this topic, I will go and create the routes for the project.

**Comment by sotch-pr35mac** [comment]
I moved that first topic over to issue #16

**Comment by sotch-pr35mac** [comment]
I don't understand what the The project specific settings are going to be. I think they should be on the projects page.

**Comment by steventhanna** [comment]
As in, how GitHub has repo specific settings?  Like settings that are specific to each repo?  Same for projects.

**Comment by sotch-pr35mac** [comment]
The breadcrumbs can be integrated into the project specific page rather easily. taking care of that right nwo

**Comment by sotch-pr35mac** [comment]
added breadcrumbs in the lastest commit.
