### ISSUE TITLE
Transition Dashboard to Analytics Page

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#12]
Because we cannot have a super specific dashboard page anymore, we should transition it to a projects overview page... And analytics page if you will.  Sort of like the graphs section on GitHub.  

- [ ] Create card UI with charts, graphs, etc. @steventhanna
- [ ] Calculate the data for said charts @sotch-pr35mac 
- [ ] Pass the data to the page / charts @sotch-pr35mac  and @steventhanna

**Comment by sotch-pr35mac** [comment]
What are these graphs actually going to have in them?

**Comment by steventhanna** [comment]
Graphs are still unknown... Maybe we could do something like ToDoist does with their graph? 
![screen shot 2015-06-27 at 10 13 54 am](https://cloud.githubusercontent.com/assets/2541678/8392612/419c6216-1cb5-11e5-8a45-0b9e0253becc.png)

**Comment by steventhanna** [comment]
So, here is what is going to happen... In order to actually ship a product, we are going to have to do away with the `dashboard` page for now.  In the future, we will make it like the `GitHub Activity Page`, but that is for a later release.  

## Be Advised
- After auth, `res.redirect('dashboard/projects')`
- Deactivate `/dashboard` routes

Hopefully, this will save us time right now, so we can get back to what really matters.
