### ISSUE TITLE
Create a better Shared Projects UX

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#13]
Up for ideas here...

**Comment by steventhanna** [comment]
Instead of sharing a project ID, it would be much easier on the user's end to simply add people by GitHub username. Then, we could have autocomplete.

We should also try and use the same lingo for skrum that GitHub uses for their own system... So collaborators, owners, etc. etc. 

### TODO
- [ ] Autocomplete with all GitHub usernames
- [ ]  Link collaborator's together

**Comment by sotch-pr35mac** [comment]
That seems like a great idea, but pretty complicated, do you think we can get that done? We just have to design a flow and UX for it and then we should be good to go when we have that figured out, but before we write any code lets figure it all out in a flow and UX

**Comment by sotch-pr35mac** [comment]
Where did you get the image above? Because a system like that seems like it would work perfect.

**Comment by steventhanna** [comment]
I already have a UI / UX in mind.  And the image above is from Todoist.  

I do not think this should be too difficult... Well, perhaps it might... Instead of the users having the project ID, and then checking permissions that way, maybe it should be the other way around... So that the project has the user list, which is of all the github usernames. 

Autocomplete should not be too bad, there are plenty of libraries out there for that.

**Comment by sotch-pr35mac** [comment]
That's already implemented as well on the server-side.
