### ISSUE TITLE
Edit content of a Project from the main projects page

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#15]
Edit the content of the projects page from `projects.ejs`.  
Must be able to edit 
- Title
- Description
- Collaborators
  Perhaps edit in a modal?

**Comment by sotch-pr35mac** [comment]
We just need to add Title, Description, and Collaborators to the project and then we are all good to go.

**Comment by sotch-pr35mac** [comment]
We just need to add Collaborators and then we are good to go, since it is a html modal and not a javascript generated one, then we can use EJS to pre-populate the fields.

**Comment by sotch-pr35mac** [comment]
This should be assigned to @steventhanna, I don't understand why I'm assigned to this.

**Comment by sotch-pr35mac** [comment]
the server side code for this is now there since issue #21 has been finished.

**Comment by steventhanna** [comment]
I need a different approach... Since the modal is not working correctly.

**Comment by sotch-pr35mac** [comment]
I don't understand, what do you need a different approach to?

**Comment by steventhanna** [comment]
Need a different approach in regards to the being able to edit projects from the `project.ejs` page, because I cannot get modals to work correctly.  I'm surprised you could not use context clues and common sense to figure out what I was talking about.

**Comment by steventhanna** [comment]
If #26 is fixed, then I can continue using the modals... Otherwise, I will have to do something different.
