### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by sotch-pr35mac** [sotch-pr35mac/skrum#17]
I'm think we could use one of the following domains:

- [skrum.net](http://www.skrum.net) for $12/year
- [skrum.social](http://www.skrum.social) for $30/year
- [skrum.builders](http://www.skrum.builders) for $30/year
- [skrum.construction](http://www.skrum.construction) for $30/year
- [skrum.computers](http://www.skrum.computers) for $30/year
- [skrum.technology](http://www.skrum.technology) for $20/year
- [skrum.io](http://www.skrum.io) for $60/year

@steventhanna what do you think about these? I am willing to go 50/50 on them.

**Comment by steventhanna** [comment]
Sadly, I like skrum.io. you?

**Comment by steventhanna** [comment]
We could also do
- [skrum.management](skrum.management) for $20/year
or even 
- [skrum.ninja](skrum.ninja) for $19/year

**Comment by sotch-pr35mac** [comment]
I think we should try and do [skrum.io](http://www.skrum.io) and if that isn't available when we are ready to buy it we can go ahead and try [skrum.ninja](http://skrum.ninja).
