### ISSUE TITLE
Breadcrumb Project Page

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#18]
The breadcrumb project page delivers the all-mighty `404` error... 

The button in question
```html
  <a id="launchProject" href="/project/<%= projects[i].name %>" class="btn btn-flat btn-accent ink-reaction">Launch</a>
```
and the response is the 404.

it might have to do with the project name's having spaces in them.  The project I tested was called `Test Project`.  When it got converted the a url, it was called `Test%20project`.  Is it possible that the system does not account for those spaces?

The full url is
```
http://127.0.0.1:1337/project/Test%20project
```

**Comment by sotch-pr35mac** [comment]
I just have to work on parsing the special characters in url strings. Working on this right now.

**Comment by sotch-pr35mac** [comment]
This actually doesn't have anything to do with the breadcrumbs... It has to do with linking to a project page.

**Comment by sotch-pr35mac** [comment]
fixed.
