### ISSUE TITLE
Edit Project Modal will not repopulate with data

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#26]
Modals are just strange... 

I am working on a better way to accomplish issue #15, so I decided to just use modals instead of a large amount of JS that would switch between "edit" mode and "view" mode... Sort of what AWF used.  

To populate the modal, I just put it inside the for loop that was doing the heavy lifting for displaying the project cards... All seemed to work ok for the first project.... But when you clicked the edit button on the second project, it would still contain the first projects data in the placeholder fields.  

Refer to lines 105 - 135 of `projects.ejs`.

Project 1 - Title `Test Project`
![screen shot 2015-07-02 at 2 54 46 pm](https://cloud.githubusercontent.com/assets/2541678/8486484/5d44ac80-20ca-11e5-88e3-e7c8e8d5f2ce.png)

Project 2 - Title `1234`
![screen shot 2015-07-02 at 2 54 51 pm](https://cloud.githubusercontent.com/assets/2541678/8486487/69556320-20ca-11e5-9b23-05c1d1ff07ea.png)

So that obviously is not good...

I was hoping @sotch-pr35mac would have an idea in how to get around this.

Once this issue is closed, we can close issue #15

**Comment by sotch-pr35mac** [comment]
This has to do with the EJS not looping through the projects correctly.
