### ISSUE TITLE
Support for first and last name

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#4]
Add support for first and last name, for the `settings.ejs` page.

**Comment by sotch-pr35mac** [comment]
can't, its all pulled from the github account information.

**Comment by sotch-pr35mac** [comment]
i guess we could have an option to override the whole name in general, but right now we are using what github gives us through passport, i guess we can go ahead and pull the sepate names from the profile as well, if that is something we need

**Comment by steventhanna** [comment]
Well, I guess there is not much inside the `settings.ejs` page right now then. Not that big of a deal
