### ISSUE TITLE
Load times abnormally long

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#5]
The load times for the site are insane... For the longest time, I was running into bugs created only because I was testing features before the site was even loaded completely! Over 10 seconds of load time! It might have something to do with issue #2.

**Comment by sotch-pr35mac** [comment]
this might have something to do with my code not being efficient, but it also might be an issue with sails js, we are going to have to figure this out, because i have been having some issue with this same thing as well.

**Comment by sotch-pr35mac** [comment]
So it looks like load times are fine when using localhost:1337, but we run into load time problems when using 127.0.0.1:1337. We have to use 127.0.0.1:1337 for the user authentication.
