### ISSUE TITLE
Review Pricing Information

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#8]
Personal
- $0 /month
- 5 Projects
- 5 shared projects

Professional
- $10 /month
- Unlimited Projects
- Unlimited shared projects

Enterprise
- $25 /month
- Unlimited projects
- Analytics coming soon

**Comment by sotch-pr35mac** [comment]
change enterprise from $25 to $15, or change professional from $10 to $20, and change "shared projects" to joined projects. 
What do you think?
Then we are all good to go!

**Comment by steventhanna** [comment]
What if we change professional to $15?  Will change to shared projects

**Comment by sotch-pr35mac** [comment]
alright i like that, that makes sense, lets do that. Closing on agreement.
